import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read = path => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
const schema = read("supabase/migrations/202607150004_training_world_schema.sql");
const logic = read("supabase/migrations/202607150005_training_world_logic.sql");
const scheduler = read("supabase/migrations/202607150006_training_world_scheduler.sql") + read("supabase/migrations/202607150007_training_catalog_schedule.sql");
const binding = read("supabase/functions/training-bind/index.ts");
const adapters = read("supabase/functions/_shared/training.ts");
const worker = read("supabase/functions/training-sync-worker/index.ts");
const frontend = read("training-world.js");
const phase2a = read("supabase/migrations/202607160010_phase2_security_frames_luogu.sql");
const phase2b = read("supabase/migrations/202607160011_phase2_regions_ability_unlocks.sql");
const phase2c = read("supabase/migrations/202607160012_phase2_monthly_learning_reports.sql");
const phase3 = read("supabase/migrations/202607160013_training_game_map.sql");
const phase3Hardening = read("supabase/migrations/202607160014_training_game_map_hardening.sql");
const activityFloor = read("supabase/migrations/202607170015_activity_score_floor.sql");
const disabledLuogu = read("supabase/functions/_disabled/training-luogu-provider.ts");
const gameMap = read("training-game-map.js");
const gameScenes = read("training-map-scenes.js");
const gameCss = read("training-game-map.css");

assert.equal((schema.match(/^\('(?:plains|bronze|silver|gold|platinum|master|legend)'/gm) || []).length, 7, "seven map definitions required");
for (const map of ["plains","bronze","silver","gold","platinum","master","legend"]) assert(schema.includes(`'${map}'`), `missing map ${map}`);
for (const weight of [".45*breadth",".25*challenge",".20*coverage",".10*stability"]) assert(logic.includes(weight), `mastery weight missing: ${weight}`);
assert.match(logic, /coalesce\(a\.canonical_problem_id,p\.problem_id\)/, "known aliases must deduplicate evidence");
assert.match(logic, /confidence>=0\.7/, "low-confidence tags must not affect mastery");
assert.match(logic, /coalesce\(s\.mastery_percent,0\)<100/, "all core regions must reach 100 before unlock");
assert.match(schema, /unique\(platform,external_user_id\)/); assert.match(schema, /unique\(platform,external_submission_id\)/);
assert.match(logic, /insert into private\.training_access_audit/); assert.match(logic, /not coalesce\(v_public,true\) and v_staff/);
assert.match(binding, /profileContainsChallenge/); assert.match(binding, /windowAttempts >= 3/); assert(!/password|cookie/i.test(binding.replace(/平台密码|Cookie/g, "")), "binding code must not accept platform credentials");
for (const host of ["codeforces.com","kenkoooo.com","atcoder.jp"]) assert(adapters.includes(host), `fixed adapter host missing: ${host}`);
assert(!adapters.includes("luogu.com.cn"), "active adapter bundle must not contact Luogu");
assert(!/\/record|X-Luogu-Type/i.test(adapters + binding + worker), "active Edge paths must not contain Luogu record scraping");
assert.match(binding, /platform_unavailable/); assert.match(worker, /account\.platform === "luogu"/);
assert.match(disabledLuogu, /awaiting_official_permission/); assert(!/fetch\s*\(/.test(disabledLuogu), "dormant provider must not make network calls");
assert(!/new URL\([^)]*body|fetch\([^)]*body\./.test(adapters + binding), "user input must not control fetch origins");
assert.match(worker, /claim_training_sync_job/); assert.match(worker, /verify_training_worker_token/); assert.match(worker, /EdgeRuntime/); assert.match(scheduler, /\*\/5 \* \* \* \*/); assert.match(scheduler, /training_worker_token/);
assert.match(frontend, /fetchTrainingHeatmap/); assert.match(frontend, /assessmentText/); assert.match(frontend, /data-bind-platform/);
assert(!/luogu/.test(frontend), "Luogu must be absent from active training UI");
for (const oldName of ["工匠营地","潮汐灯塔","机关矿道","流沙工坊","浮空铸造厂","时空船坞","万象裂谷"]) assert(!phase2b.includes(`'${oldName}'`), `fantasy-only region name remains: ${oldName}`);
for (const threshold of ["v_average>=1100","v_average>=1400","v_average>=1700","v_average>=2000","v_average>=2400","v_average>=2800"]) assert(phase2b.includes(threshold), `direct unlock threshold missing: ${threshold}`);
assert.match(phase2b, /least\(20,greatest\(5,ceil\(v_n\*\.25\)/); assert.match(phase2b, /'reason','ability_average'/);
assert.match(phase2a, /normalize\(coalesce\(split_part\(new\.email,'@',1\),''\),NFKC\)/); assert.match(phase2a, /'banned',true/);
for (const frame of ["expedition_bronze","laurel_streak","ink_author","community_crown","balanced_emerald","map_conqueror","chromatic_chosen"]) assert(phase2a.includes(`('${frame}'`), `avatar frame missing: ${frame}`);
assert.match(phase2c, /unique\(user_id,report_month\)/); assert.match(phase2c, /Asia\/Shanghai/); assert.match(phase2c, /extract\(day from \(now\(\) at time zone 'Asia\/Shanghai'\)\).*<>2/);
assert.match(phase2c, /monthly_learning_reports_own_read/); assert.match(phase2c, /20 16 \* \* \*/);
assert.match(phase2c, /monthly_skill_snapshots_client_deny/); assert.match(phase2c, /'mastery_delta'/);
assert.match(phase3, /create table if not exists public\.training_game_state/);
assert.match(phase3, /create table if not exists public\.guardian_challenges/);
assert.match(phase3, /private\.complete_training_game_events/);
assert.match(phase3, /training_game_state_own_read/);
assert.match(phase3Hardening, /game_map_enabled/);
assert.match(activityFloor, /greatest\(-30,q\.raw_score\)::integer as score/);
assert.match(gameMap, /from "pixi\.js"/);
assert.match(gameMap, /travelTo\(item, region, quest\)/);
assert.match(gameMap, /playUnlock\(event/);
assert.match(gameScenes, /ALL_REGION_CODES/);
assert.match(gameScenes, /!== 41/);
assert.match(gameScenes, /route graph is disconnected/);
assert.match(gameCss, /\.game-region-drawer/);
assert.match(gameCss, /\.map-unlock-cinematic/);
assert.match(gameCss, /prefers-reduced-motion:reduce/);
assert.match(gameCss, /\.game-map-fallback/);

console.log("Algorithm Expedition checks passed: maps, scoring, privacy, adapters, queue, game scenes and UI contracts.");
